# Utilizo esse docker-compose.yml, em conjunto com o arquivo Dockerfile, para projetos em Laravel
# Deve-se substituir "nome_projeto" pelo nome real do projeto
version: '1'
services:
  laravel-docker:
    build: ./
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/nome_projeto/
    restart: always
    networks:
      - docker

networks:
  docker: 
    driver: bridge